id: A1491437D
title: Aspiration for Rebirth in Sukhāvatī
type: translation
pechas:
- I3A9FC999
- ID319B397
- IE6BFE2E6
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:41:07.152626
  last_modified_at: 2023-01-04 11:41:07.152638
  collections:
  - Dodrupchen Jigme Tenpe Nyima Series
  - Works of Tibetan Masters
alignment_to_base:
  I3A9FC999/FBBB: 3F05
  ID319B397/4EEE: 3F05
  IE6BFE2E6/B040: 3F05
